## Problem 22

In [1]:
library(igraph)
library(data.table)


Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union



In [66]:
neighbors = read.table("../gplus/109327480479767108490.feat", colClasses = "character")
edges = read.table("../gplus/109327480479767108490.edges", colClasses = "character")
colnames(neighbors)[1] = "v1"
colnames(neighbors)[2] = "v2"
neighbors <- subset(neighbors, select=c("v1", "v2"))
id = strsplit("../gplus/115625564993990145546", "/")[[1]][[3]]
edge_list = as.vector(t(edges))
temp = neighbors[1]
neighbors[1] = id
neighbors[2] = temp
g <- graph_from_data_frame(neighbors, directed = TRUE, vertices = NULL)
g <- add_edges(g, edge_list)
walktrap <- walktrap.community(g)
color_vector = walktrap$membership+1
vertex_vector = rep(4,vcount(g))
vertex_vector[1]=6



In [67]:
PATH = "../gplus/109327480479767108490.circles"
openFile_circle = file(PATH, open="r")
linesInCircle = readLines(openFile_circle)
circlemember = seq_len(0)
a=seq_len(0)
circlemember=seq_len(0)
for (i in 1:length(linesInCircle)){
    circlex=linesInCircle[i]
    circlememberx= strsplit(circlex, "\t")[[1]] 
    circlemember=c(circlemember,circlememberx)
    a=c(a,(length(circlememberx)-1))
}
circlemember_new=unique(circlemember)
print(a)

[1] 330 346 419


In [68]:
counter = rep(0, length(walktrap))
for (i in circlemember_new) {
    for (j in 1:length(walktrap)) {
        if (i %in% walktrap[[j]]) {
            counter[[j]] <- counter[[j]] + 1
        }
        
    }
}

In [69]:
print(counter)

[1] 279 397  75  13


In [70]:
circlemember = seq_len(0)
circlemember=seq_len(0)
C <- matrix(0, nrow = 3, ncol = 4)
col <- 1
row <- 1
for (i in 1:length(linesInCircle)){
    circlex=linesInCircle[i]
    circlememberx= strsplit(circlex, "\t")[[1]]
    for (j in 1:length(walktrap)) {
        for (k in walktrap[[j]]) {
            if (k %in% circlememberx) {
                C[i, j] <- C[i, j] + 1
            }
        }
    }
    circlemember=c(circlemember,circlememberx)
}


In [71]:
print(C)

     [,1] [,2] [,3] [,4]
[1,]  251    4   75    0
[2,]  267    4   75    0
[3,]   13  393    0   13


In [77]:
N=length(circlemember_new)-3
print(N)

HC=0
for (i in 1:length(linesInCircle)){
    HC=HC-(a[i]/N*(log(a[i]/N)))
    }
print(HC)

[1] 764
[1] 1.050779


In [76]:
HK=0
for (i in 1:length(counter)){
    HK=HK-(counter[i]/N*(log(counter[i]/N)))
    print(HK)
}
print(HK)

[1] 0.3678695
[1] 0.708038
[1] 0.9358927
[1] 1.005208
[1] 1.005208


In [94]:
HCK=0
for (i in 1:length(linesInCircle)){
    for (j in 1:length(counter)){
        log=log(C[i,j]/counter[j])
        if (C[i,j]/counter[j]==0){
            log=0
        }
        HCK=HCK-((C[i,j]/N)*log)
    }
}
print(HCK)

[1] 0.1556361


In [101]:
HKC=0
for (i in 1:length(linesInCircle)){
    for (j in 1:length(counter)){
        log=log(C[i,j]/a[i])
        if (C[i,j]/counter[j]==0){
            log=0
        }
        HKC=HKC-((C[i,j]/N)*log)
    }
}
print(HKC)

[1] 0.6736162


In [103]:
h1=1-(HCK/HC)
print(h1)
c1=1-(HKC/HK)
print(c1)

[1] 0.2108217
[1] 0.3298739


In [38]:
neighbors = read.table("../gplus/115625564993990145546.feat", colClasses = "character")
edges = read.table("../gplus/115625564993990145546.edges", colClasses = "character")
colnames(neighbors)[1] = "v1"
colnames(neighbors)[2] = "v2"
neighbors <- subset(neighbors, select=c("v1", "v2"))
id = strsplit("../gplus/115625564993990145546", "/")[[1]][[3]]
edge_list = as.vector(t(edges))
temp = neighbors[1]
neighbors[1] = id
neighbors[2] = temp
g <- graph_from_data_frame(neighbors, directed = TRUE, vertices = NULL)
g <- add_edges(g, edge_list)
walktrap <- walktrap.community(g)
color_vector = walktrap$membership+1
vertex_vector = rep(4,vcount(g))
vertex_vector[1]=6
print(modularity(walktrap))

[1] 0.3128763


In [107]:
neighbors = read.table("../gplus/115625564993990145546.feat", colClasses = "character")
edges = read.table("../gplus/115625564993990145546.edges", colClasses = "character")
colnames(neighbors)[1] = "v1"
colnames(neighbors)[2] = "v2"
neighbors <- subset(neighbors, select=c("v1", "v2"))
id = strsplit("../gplus/115625564993990145546", "/")[[1]][[3]]
edge_list = as.vector(t(edges))
temp = neighbors[1]
neighbors[1] = id
neighbors[2] = temp
g <- graph_from_data_frame(neighbors, directed = TRUE, vertices = NULL)
g <- add_edges(g, edge_list)
walktrap <- walktrap.community(g)
color_vector = walktrap$membership+1
vertex_vector = rep(4,vcount(g))
vertex_vector[1]=6
print(modularity(walktrap))

[1] 0.3128763


In [108]:
PATH = "../gplus/115625564993990145546.circles"
openFile_circle = file(PATH, open="r")
linesInCircle = readLines(openFile_circle)
circlemember = seq_len(0)
a=seq_len(0)
circlemember=seq_len(0)
for (i in 1:length(linesInCircle)){
    circlex=linesInCircle[i]
    circlememberx= strsplit(circlex, "\t")[[1]] 
    circlemember=c(circlemember,circlememberx)
    a=c(a,(length(circlememberx)-1))
}
circlemember_new=unique(circlemember)
print(a)

 [1]   6   9 169 276 325  93  73 338  46  62 338 255 485   7 260 363 188 327 314
[20]  48 489 276  79 373  67  10 354  73 300 362 102


In [109]:
counter = rep(0, length(walktrap))
for (i in circlemember_new) {
    for (j in 1:length(walktrap)) {
        if (i %in% walktrap[[j]]) {
            counter[[j]] <- counter[[j]] + 1
        }
        
    }
}

In [110]:
print(counter)

 [1]   1   6   0 165 231 323   1   0   0   0   0   0   0   0   0   0   0   0   0
[20]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0


In [112]:
circlemember = seq_len(0)
circlemember=seq_len(0)
C <- matrix(0, nrow = length(linesInCircle), ncol = length(counter))
col <- 1
row <- 1
for (i in 1:length(linesInCircle)){
    circlex=linesInCircle[i]
    circlememberx= strsplit(circlex, "\t")[[1]]
    for (j in 1:length(walktrap)) {
        for (k in walktrap[[j]]) {
            if (k %in% circlememberx) {
                C[i, j] <- C[i, j] + 1
            }
        }
    }
    circlemember=c(circlemember,circlememberx)
}

In [113]:
print(C)

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,]    0    0    0    3    0    3    0    0    0     0     0     0     0
 [2,]    0    0    0    4    0    5    0    0    0     0     0     0     0
 [3,]    0    3    0   18    0  148    0    0    0     0     0     0     0
 [4,]    0    3    0   21    0  252    0    0    0     0     0     0     0
 [5,]    0    1    0   39    0  285    0    0    0     0     0     0     0
 [6,]    0    3    0    8    0   82    0    0    0     0     0     0     0
 [7,]    0    0    0   63    0   10    0    0    0     0     0     0     0
 [8,]    0    2    0   86  229   21    0    0    0     0     0     0     0
 [9,]    0    1    0   31    1   13    0    0    0     0     0     0     0
[10,]    0    0    0   57    0    5    0    0    0     0     0     0     0
[11,]    0    4    0   88   77  168    1    0    0     0     0     0     0
[12,]    0    2    0   20  229    4    0    0    0     0     0     0     0
[13,]    1    3    0  143

In [114]:
N=length(circlemember_new)-3
print(N)

HC=0
for (i in 1:length(linesInCircle)){
    HC=HC-(a[i]/N*(log(a[i]/N)))
    }
print(HC)

[1] 755
[1] 8.474911


In [117]:
HK=0
for (i in 1:length(counter)){
    log=log(counter[i]/N)
    if (counter[i]/N==0){
        log=0
    }
    HK=HK-(counter[i]/N*(log))
}
print(HK)

[1] 1.113923


In [122]:
HCK=0
for (i in 1:length(linesInCircle)){
    for (j in 1:length(counter)){
        log=log(C[i,j]/counter[j])
        if (C[i,j] == 0 ||counter[j]==0){
            log=0
        }
        HCK=HCK-((C[i,j]/N)*log)
    }
}
print(HCK)

[1] 4.441321


In [123]:
HKC=0
for (i in 1:length(linesInCircle)){
    for (j in 1:length(counter)){
        log=log(C[i,j]/a[i])
        if (C[i,j]==0||counter[j]==0){
            log=0
        }
        HKC=HKC-((C[i,j]/N)*log)
    }
}
print(HKC)

[1] 5.050819


In [126]:
h2=1-(HCK/HC)
print(h2)
c2=1-(HKC/HK)
print(c2)


[1] 0.4759448
[1] -3.534262


In [127]:
edges = fread("../gplus/101373961279443806744.edges", colClasses = "character")
neighbors = fread("../gplus/101373961279443806744.feat", colClasses = "character", select=c(1,2))
id = strsplit("../gplus/101373961279443806744", "/")[[1]][[3]]
temp = neighbors[, 1]
neighbors[, 1] = id
neighbors[, 2] = temp
colnames(edges )[1] = "v1"
colnames(edges)[2] = "v2"
colnames(neighbors)[1] = "v1"
colnames(neighbors)[2] = "v2"
result <- rbind(neighbors, edges)
g <- graph_from_data_frame(result, directed = TRUE, vertices = NULL)
walktrap <- walktrap.community(g)
color_vector = walktrap$membership+1
vertex_vector = rep(4,vcount(g))
vertex_vector[1]=6

In [128]:
PATH = "../gplus/101373961279443806744.circles"
openFile_circle = file(PATH, open="r")
linesInCircle = readLines(openFile_circle)
circlemember = seq_len(0)
a=seq_len(0)
circlemember=seq_len(0)
for (i in 1:length(linesInCircle)){
    circlex=linesInCircle[i]
    circlememberx= strsplit(circlex, "\t")[[1]] 
    circlemember=c(circlemember,circlememberx)
    a=c(a,(length(circlememberx)-1))
}
circlemember_new=unique(circlemember)
print(a)

[1] 471 445 430


In [129]:
counter = rep(0, length(walktrap))
for (i in circlemember_new) {
    for (j in 1:length(walktrap)) {
        if (i %in% walktrap[[j]]) {
            counter[[j]] <- counter[[j]] + 1
        }
        
    }
}

In [130]:
print(counter)

 [1]  10  93   0 394  24   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[20]   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
[39]   0   0   0   0   0   0   0   0   0   0   0


In [131]:
circlemember = seq_len(0)
circlemember=seq_len(0)
C <- matrix(0, nrow = length(linesInCircle), ncol = length(counter))
col <- 1
row <- 1
for (i in 1:length(linesInCircle)){
    circlex=linesInCircle[i]
    circlememberx= strsplit(circlex, "\t")[[1]]
    for (j in 1:length(walktrap)) {
        for (k in walktrap[[j]]) {
            if (k %in% circlememberx) {
                C[i, j] <- C[i, j] + 1
            }
        }
    }
    circlemember=c(circlemember,circlememberx)
}

In [132]:
print(C)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]    8   88    0  355   20    0    0    0    0     0     0     0     0     0
[2,]    8   81    0  340   16    0    0    0    0     0     0     0     0     0
[3,]    7   83    0  320   20    0    0    0    0     0     0     0     0     0
     [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     0     0     0     0     0     0     0
[3,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
[1,]     0     0     0     0     0     0     0     0     0     0     0     0
[2,]     0     0     0     0     0     0     0     0     0     0     0     0
[3,]     0     0     0     0     0     0     0     0     0     0     0     0
     [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48]

In [133]:
N=length(circlemember_new)-3
print(N)

HC=0
for (i in 1:length(linesInCircle)){
    HC=HC-(a[i]/N*(log(a[i]/N)))
    }
print(HC)

[1] 521
[1] 0.38432


In [134]:
HK=0
for (i in 1:length(counter)){
    log=log(counter[i]/N)
    if (counter[i]/N==0){
        log=0
    }
    HK=HK-(counter[i]/N*(log))
}
print(HK)

[1] 0.7365309


In [135]:
HCK=0
for (i in 1:length(linesInCircle)){
    for (j in 1:length(counter)){
        log=log(C[i,j]/counter[j])
        if (C[i,j] == 0 ||counter[j]==0){
            log=0
        }
        HCK=HCK-((C[i,j]/N)*log)
    }
}
print(HCK)

[1] 0.3820206


In [136]:
HKC=0
for (i in 1:length(linesInCircle)){
    for (j in 1:length(counter)){
        log=log(C[i,j]/a[i])
        if (C[i,j]==0||counter[j]==0){
            log=0
        }
        HKC=HKC-((C[i,j]/N)*log)
    }
}
print(HKC)

[1] 1.880806


In [138]:
h3=1-(HCK/HC)
print(h3)
c3=1-(HKC/HK)
print(c3)

[1] 0.005982916
[1] -1.553601
